"""Drop Subject table and link directly to StudyRoom

Revision ID: 3740339abe36
Revises: 047967431bb9
Create Date: 2026-07-13 09:59:42.456384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3740339abe36'
down_revision: Union[str, Sequence[str], None] = '047967431bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_room_id'), table_name='subject')
    op.drop_table('subject')
    op.add_column('chat_session', sa.Column('room_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_chat_session_subject_id'), table_name='chat_session')
    op.create_index(op.f('ix_chat_session_room_id'), 'chat_session', ['room_id'], unique=False)
    op.drop_constraint(op.f('chat_session_subject_id_fkey'), 'chat_session', type_='foreignkey')
    op.create_foreign_key(None, 'chat_session', 'study_room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_session', 'subject_id')
    op.add_column('document', sa.Column('room_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_document_subject_id'), table_name='document')
    op.create_index(op.f('ix_document_room_id'), 'document', ['room_id'], unique=False)
    op.drop_constraint(op.f('document_subject_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'study_room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document', 'subject_id')
    op.add_column('flashcard_deck', sa.Column('room_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_flashcard_deck_subject_id'), table_name='flashcard_deck')
    op.create_index(op.f('ix_flashcard_deck_room_id'), 'flashcard_deck', ['room_id'], unique=False)
    op.drop_constraint(op.f('flashcard_deck_subject_id_fkey'), 'flashcard_deck', type_='foreignkey')
    op.create_foreign_key(None, 'flashcard_deck', 'study_room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('flashcard_deck', 'subject_id')
    op.add_column('quiz', sa.Column('room_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_quiz_subject_id'), table_name='quiz')
    op.create_index(op.f('ix_quiz_room_id'), 'quiz', ['room_id'], unique=False)
    op.drop_constraint(op.f('quiz_subject_id_fkey'), 'quiz', type_='foreignkey')
    op.create_foreign_key(None, 'quiz', 'study_room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quiz', 'subject_id')
    op.add_column('summary', sa.Column('room_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_summary_subject_id'), table_name='summary')
    op.create_index(op.f('ix_summary_room_id'), 'summary', ['room_id'], unique=False)
    op.drop_constraint(op.f('summary_subject_id_fkey'), 'summary', type_='foreignkey')
    op.create_foreign_key(None, 'summary', 'study_room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('summary', 'subject_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'summary', type_='foreignkey')
    op.create_foreign_key(op.f('summary_subject_id_fkey'), 'summary', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_summary_room_id'), table_name='summary')
    op.create_index(op.f('ix_summary_subject_id'), 'summary', ['subject_id'], unique=False)
    op.drop_column('summary', 'room_id')
    op.add_column('quiz', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_subject_id_fkey'), 'quiz', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_quiz_room_id'), table_name='quiz')
    op.create_index(op.f('ix_quiz_subject_id'), 'quiz', ['subject_id'], unique=False)
    op.drop_column('quiz', 'room_id')
    op.add_column('flashcard_deck', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flashcard_deck', type_='foreignkey')
    op.create_foreign_key(op.f('flashcard_deck_subject_id_fkey'), 'flashcard_deck', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_flashcard_deck_room_id'), table_name='flashcard_deck')
    op.create_index(op.f('ix_flashcard_deck_subject_id'), 'flashcard_deck', ['subject_id'], unique=False)
    op.drop_column('flashcard_deck', 'room_id')
    op.add_column('document', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_subject_id_fkey'), 'document', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_room_id'), table_name='document')
    op.create_index(op.f('ix_document_subject_id'), 'document', ['subject_id'], unique=False)
    op.drop_column('document', 'room_id')
    op.add_column('chat_session', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.create_foreign_key(op.f('chat_session_subject_id_fkey'), 'chat_session', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_session_room_id'), table_name='chat_session')
    op.create_index(op.f('ix_chat_session_subject_id'), 'chat_session', ['subject_id'], unique=False)
    op.drop_column('chat_session', 'room_id')
    op.create_table('subject',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['study_room.id'], name=op.f('subject_room_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subject_pkey'))
    )
    op.create_index(op.f('ix_subject_room_id'), 'subject', ['room_id'], unique=False)
    # ### end Alembic commands ###
