"""remove tenant_id from user table to support multi-tenant

Revision ID: 50f6effe7c5f
Revises: 8f6c0f3830c5
Create Date: 2026-07-08 00:22:58.203939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f6effe7c5f'
down_revision: Union[str, Sequence[str], None] = '8f6c0f3830c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tenant_id', sa.VARCHAR(length=100), server_default=sa.text("'default-tenant'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
