"""Add user_id and description to flashcard_deck

Revision ID: 5af1adaa050b
Revises: a139a815175c
Create Date: 2026-07-12 16:14:50.042018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af1adaa050b'
down_revision: Union[str, Sequence[str], None] = 'a139a815175c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_deck_view',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_deck.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_deck_view_deck_id'), 'flashcard_deck_view', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcard_deck_view_viewer_id'), 'flashcard_deck_view', ['viewer_id'], unique=False)
    op.add_column('flashcard_deck', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('flashcard_deck', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_flashcard_deck_user_id'), 'flashcard_deck', ['user_id'], unique=False)
    op.create_foreign_key(None, 'flashcard_deck', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcard_deck', type_='foreignkey')
    op.drop_index(op.f('ix_flashcard_deck_user_id'), table_name='flashcard_deck')
    op.drop_column('flashcard_deck', 'description')
    op.drop_column('flashcard_deck', 'user_id')
    op.drop_index(op.f('ix_flashcard_deck_view_viewer_id'), table_name='flashcard_deck_view')
    op.drop_index(op.f('ix_flashcard_deck_view_deck_id'), table_name='flashcard_deck_view')
    op.drop_table('flashcard_deck_view')
    # ### end Alembic commands ###
