"""update quiz_attempt and add attempt_answer

Revision ID: bbf464fa9cfd
Revises: d3ebb8bf154d
Create Date: 2026-07-10 10:32:12.630434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf464fa9cfd'
down_revision: Union[str, Sequence[str], None] = 'd3ebb8bf154d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_answer_attempt_id'), 'attempt_answer', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answer_question_id'), 'attempt_answer', ['question_id'], unique=False)
    op.add_column('quiz_attempt', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('quiz_attempt', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('quiz_attempt', 'completed_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempt', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.alter_column('quiz_attempt', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('quiz_attempt', 'started_at')
    op.drop_index(op.f('ix_attempt_answer_question_id'), table_name='attempt_answer')
    op.drop_index(op.f('ix_attempt_answer_attempt_id'), table_name='attempt_answer')
    op.drop_table('attempt_answer')
    # ### end Alembic commands ###
